// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hawactormsg.proto

package naogateway.value;

public final class Hawactormsg {
    private Hawactormsg() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface HAWActorRPCRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string module = 1;
        boolean hasModule();

        String getModule();

        // required string method = 2;
        boolean hasMethod();

        String getMethod();

        // repeated .NaoAdapter.type.MixedValue params = 3;
        java.util.List<MixedValue>
        getParamsList();

        MixedValue getParams(int index);

        int getParamsCount();

        java.util.List<? extends MixedValueOrBuilder>
        getParamsOrBuilderList();

        MixedValueOrBuilder getParamsOrBuilder(
                int index);
    }

    public static final class HAWActorRPCRequest extends
            com.google.protobuf.GeneratedMessage
            implements HAWActorRPCRequestOrBuilder {
        // Use HAWActorRPCRequest.newBuilder() to construct.
        private HAWActorRPCRequest(Builder builder) {
            super(builder);
        }

        private HAWActorRPCRequest(boolean noInit) {
        }

        private static final HAWActorRPCRequest defaultInstance;

        public static HAWActorRPCRequest getDefaultInstance() {
            return defaultInstance;
        }

        public HAWActorRPCRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Hawactormsg.internal_static_nao_HAWActorRPCRequest_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Hawactormsg.internal_static_nao_HAWActorRPCRequest_fieldAccessorTable;
        }

        private int bitField0_;
        // required string module = 1;
        public static final int MODULE_FIELD_NUMBER = 1;
        private Object module_;

        public boolean hasModule() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getModule() {
            Object ref = module_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    module_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getModuleBytes() {
            Object ref = module_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                module_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string method = 2;
        public static final int METHOD_FIELD_NUMBER = 2;
        private Object method_;

        public boolean hasMethod() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getMethod() {
            Object ref = method_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    method_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getMethodBytes() {
            Object ref = method_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                method_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // repeated .NaoAdapter.type.MixedValue params = 3;
        public static final int PARAMS_FIELD_NUMBER = 3;
        private java.util.List<MixedValue> params_;

        public java.util.List<MixedValue> getParamsList() {
            return params_;
        }

        public java.util.List<? extends MixedValueOrBuilder>
        getParamsOrBuilderList() {
            return params_;
        }

        public int getParamsCount() {
            return params_.size();
        }

        public MixedValue getParams(int index) {
            return params_.get(index);
        }

        public MixedValueOrBuilder getParamsOrBuilder(
                int index) {
            return params_.get(index);
        }

        private void initFields() {
            module_ = "";
            method_ = "";
            params_ = java.util.Collections.emptyList();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasModule()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMethod()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getModuleBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getMethodBytes());
            }
            for (int i = 0; i < params_.size(); i++) {
                output.writeMessage(3, params_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getModuleBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getMethodBytes());
            }
            for (int i = 0; i < params_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, params_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static HAWActorRPCRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static HAWActorRPCRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static HAWActorRPCRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static HAWActorRPCRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static HAWActorRPCRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static HAWActorRPCRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static HAWActorRPCRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static HAWActorRPCRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static HAWActorRPCRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static HAWActorRPCRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(HAWActorRPCRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements HAWActorRPCRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Hawactormsg.internal_static_nao_HAWActorRPCRequest_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Hawactormsg.internal_static_nao_HAWActorRPCRequest_fieldAccessorTable;
            }

            // Construct using NaoAdapter.type.Hawactormsg.HAWActorRPCRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getParamsFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                module_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                method_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                if (paramsBuilder_ == null) {
                    params_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    paramsBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return HAWActorRPCRequest.getDescriptor();
            }

            public HAWActorRPCRequest getDefaultInstanceForType() {
                return HAWActorRPCRequest.getDefaultInstance();
            }

            public HAWActorRPCRequest build() {
                HAWActorRPCRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private HAWActorRPCRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                HAWActorRPCRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public HAWActorRPCRequest buildPartial() {
                HAWActorRPCRequest result = new HAWActorRPCRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.module_ = module_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.method_ = method_;
                if (paramsBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        params_ = java.util.Collections.unmodifiableList(params_);
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.params_ = params_;
                } else {
                    result.params_ = paramsBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof HAWActorRPCRequest) {
                    return mergeFrom((HAWActorRPCRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(HAWActorRPCRequest other) {
                if (other == HAWActorRPCRequest.getDefaultInstance()) return this;
                if (other.hasModule()) {
                    setModule(other.getModule());
                }
                if (other.hasMethod()) {
                    setMethod(other.getMethod());
                }
                if (paramsBuilder_ == null) {
                    if (!other.params_.isEmpty()) {
                        if (params_.isEmpty()) {
                            params_ = other.params_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureParamsIsMutable();
                            params_.addAll(other.params_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.params_.isEmpty()) {
                        if (paramsBuilder_.isEmpty()) {
                            paramsBuilder_.dispose();
                            paramsBuilder_ = null;
                            params_ = other.params_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                            paramsBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getParamsFieldBuilder() : null;
                        } else {
                            paramsBuilder_.addAllMessages(other.params_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasModule()) {

                    return false;
                }
                if (!hasMethod()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            module_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            method_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            MixedValue.Builder subBuilder = MixedValue.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addParams(subBuilder.buildPartial());
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string module = 1;
            private Object module_ = "";

            public boolean hasModule() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getModule() {
                Object ref = module_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    module_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setModule(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                module_ = value;
                onChanged();
                return this;
            }

            public Builder clearModule() {
                bitField0_ = (bitField0_ & ~0x00000001);
                module_ = getDefaultInstance().getModule();
                onChanged();
                return this;
            }

            void setModule(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                module_ = value;
                onChanged();
            }

            // required string method = 2;
            private Object method_ = "";

            public boolean hasMethod() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getMethod() {
                Object ref = method_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    method_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setMethod(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                method_ = value;
                onChanged();
                return this;
            }

            public Builder clearMethod() {
                bitField0_ = (bitField0_ & ~0x00000002);
                method_ = getDefaultInstance().getMethod();
                onChanged();
                return this;
            }

            void setMethod(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                method_ = value;
                onChanged();
            }

            // repeated .NaoAdapter.type.MixedValue params = 3;
            private java.util.List<MixedValue> params_ =
                    java.util.Collections.emptyList();

            private void ensureParamsIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    params_ = new java.util.ArrayList<MixedValue>(params_);
                    bitField0_ |= 0x00000004;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    MixedValue, MixedValue.Builder, MixedValueOrBuilder> paramsBuilder_;

            public java.util.List<MixedValue> getParamsList() {
                if (paramsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(params_);
                } else {
                    return paramsBuilder_.getMessageList();
                }
            }

            public int getParamsCount() {
                if (paramsBuilder_ == null) {
                    return params_.size();
                } else {
                    return paramsBuilder_.getCount();
                }
            }

            public MixedValue getParams(int index) {
                if (paramsBuilder_ == null) {
                    return params_.get(index);
                } else {
                    return paramsBuilder_.getMessage(index);
                }
            }

            public Builder setParams(
                    int index, MixedValue value) {
                if (paramsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureParamsIsMutable();
                    params_.set(index, value);
                    onChanged();
                } else {
                    paramsBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setParams(
                    int index, MixedValue.Builder builderForValue) {
                if (paramsBuilder_ == null) {
                    ensureParamsIsMutable();
                    params_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    paramsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addParams(MixedValue value) {
                if (paramsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureParamsIsMutable();
                    params_.add(value);
                    onChanged();
                } else {
                    paramsBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addParams(
                    int index, MixedValue value) {
                if (paramsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureParamsIsMutable();
                    params_.add(index, value);
                    onChanged();
                } else {
                    paramsBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addParams(
                    MixedValue.Builder builderForValue) {
                if (paramsBuilder_ == null) {
                    ensureParamsIsMutable();
                    params_.add(builderForValue.build());
                    onChanged();
                } else {
                    paramsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addParams(
                    int index, MixedValue.Builder builderForValue) {
                if (paramsBuilder_ == null) {
                    ensureParamsIsMutable();
                    params_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    paramsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllParams(
                    Iterable<? extends MixedValue> values) {
                if (paramsBuilder_ == null) {
                    ensureParamsIsMutable();
                    super.addAll(values, params_);
                    onChanged();
                } else {
                    paramsBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearParams() {
                if (paramsBuilder_ == null) {
                    params_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                } else {
                    paramsBuilder_.clear();
                }
                return this;
            }

            public Builder removeParams(int index) {
                if (paramsBuilder_ == null) {
                    ensureParamsIsMutable();
                    params_.remove(index);
                    onChanged();
                } else {
                    paramsBuilder_.remove(index);
                }
                return this;
            }

            public MixedValue.Builder getParamsBuilder(
                    int index) {
                return getParamsFieldBuilder().getBuilder(index);
            }

            public MixedValueOrBuilder getParamsOrBuilder(
                    int index) {
                if (paramsBuilder_ == null) {
                    return params_.get(index);
                } else {
                    return paramsBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends MixedValueOrBuilder>
            getParamsOrBuilderList() {
                if (paramsBuilder_ != null) {
                    return paramsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(params_);
                }
            }

            public MixedValue.Builder addParamsBuilder() {
                return getParamsFieldBuilder().addBuilder(
                        MixedValue.getDefaultInstance());
            }

            public MixedValue.Builder addParamsBuilder(
                    int index) {
                return getParamsFieldBuilder().addBuilder(
                        index, MixedValue.getDefaultInstance());
            }

            public java.util.List<MixedValue.Builder>
            getParamsBuilderList() {
                return getParamsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    MixedValue, MixedValue.Builder, MixedValueOrBuilder>
            getParamsFieldBuilder() {
                if (paramsBuilder_ == null) {
                    paramsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            MixedValue, MixedValue.Builder, MixedValueOrBuilder>(
                            params_,
                            ((bitField0_ & 0x00000004) == 0x00000004),
                            getParentForChildren(),
                            isClean());
                    params_ = null;
                }
                return paramsBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:NaoAdapter.type.HAWActorRPCRequest)
        }

        static {
            defaultInstance = new HAWActorRPCRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:NaoAdapter.type.HAWActorRPCRequest)
    }

    public interface HAWActorRPCResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional .NaoAdapter.type.MixedValue returnval = 1;
        boolean hasReturnval();

        MixedValue getReturnval();

        MixedValueOrBuilder getReturnvalOrBuilder();

        // optional string error = 2;
        boolean hasError();

        String getError();
    }

    public static final class HAWActorRPCResponse extends
            com.google.protobuf.GeneratedMessage
            implements HAWActorRPCResponseOrBuilder {
        // Use HAWActorRPCResponse.newBuilder() to construct.
        private HAWActorRPCResponse(Builder builder) {
            super(builder);
        }

        private HAWActorRPCResponse(boolean noInit) {
        }

        private static final HAWActorRPCResponse defaultInstance;

        public static HAWActorRPCResponse getDefaultInstance() {
            return defaultInstance;
        }

        public HAWActorRPCResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Hawactormsg.internal_static_nao_HAWActorRPCResponse_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Hawactormsg.internal_static_nao_HAWActorRPCResponse_fieldAccessorTable;
        }

        private int bitField0_;
        // optional .NaoAdapter.type.MixedValue returnval = 1;
        public static final int RETURNVAL_FIELD_NUMBER = 1;
        private MixedValue returnval_;

        public boolean hasReturnval() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public MixedValue getReturnval() {
            return returnval_;
        }

        public MixedValueOrBuilder getReturnvalOrBuilder() {
            return returnval_;
        }

        // optional string error = 2;
        public static final int ERROR_FIELD_NUMBER = 2;
        private Object error_;

        public boolean hasError() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getError() {
            Object ref = error_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    error_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getErrorBytes() {
            Object ref = error_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                error_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            returnval_ = MixedValue.getDefaultInstance();
            error_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeMessage(1, returnval_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getErrorBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, returnval_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getErrorBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static HAWActorRPCResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static HAWActorRPCResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static HAWActorRPCResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static HAWActorRPCResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static HAWActorRPCResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static HAWActorRPCResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static HAWActorRPCResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static HAWActorRPCResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static HAWActorRPCResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static HAWActorRPCResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(HAWActorRPCResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements HAWActorRPCResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Hawactormsg.internal_static_nao_HAWActorRPCResponse_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Hawactormsg.internal_static_nao_HAWActorRPCResponse_fieldAccessorTable;
            }

            // Construct using NaoAdapter.type.Hawactormsg.HAWActorRPCResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getReturnvalFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                if (returnvalBuilder_ == null) {
                    returnval_ = MixedValue.getDefaultInstance();
                } else {
                    returnvalBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                error_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return HAWActorRPCResponse.getDescriptor();
            }

            public HAWActorRPCResponse getDefaultInstanceForType() {
                return HAWActorRPCResponse.getDefaultInstance();
            }

            public HAWActorRPCResponse build() {
                HAWActorRPCResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private HAWActorRPCResponse buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                HAWActorRPCResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public HAWActorRPCResponse buildPartial() {
                HAWActorRPCResponse result = new HAWActorRPCResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                if (returnvalBuilder_ == null) {
                    result.returnval_ = returnval_;
                } else {
                    result.returnval_ = returnvalBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.error_ = error_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof HAWActorRPCResponse) {
                    return mergeFrom((HAWActorRPCResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(HAWActorRPCResponse other) {
                if (other == HAWActorRPCResponse.getDefaultInstance()) return this;
                if (other.hasReturnval()) {
                    mergeReturnval(other.getReturnval());
                }
                if (other.hasError()) {
                    setError(other.getError());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            MixedValue.Builder subBuilder = MixedValue.newBuilder();
                            if (hasReturnval()) {
                                subBuilder.mergeFrom(getReturnval());
                            }
                            input.readMessage(subBuilder, extensionRegistry);
                            setReturnval(subBuilder.buildPartial());
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            error_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional .NaoAdapter.type.MixedValue returnval = 1;
            private MixedValue returnval_ = MixedValue.getDefaultInstance();
            private com.google.protobuf.SingleFieldBuilder<
                    MixedValue, MixedValue.Builder, MixedValueOrBuilder> returnvalBuilder_;

            public boolean hasReturnval() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public MixedValue getReturnval() {
                if (returnvalBuilder_ == null) {
                    return returnval_;
                } else {
                    return returnvalBuilder_.getMessage();
                }
            }

            public Builder setReturnval(MixedValue value) {
                if (returnvalBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    returnval_ = value;
                    onChanged();
                } else {
                    returnvalBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            public Builder setReturnval(
                    MixedValue.Builder builderForValue) {
                if (returnvalBuilder_ == null) {
                    returnval_ = builderForValue.build();
                    onChanged();
                } else {
                    returnvalBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            public Builder mergeReturnval(MixedValue value) {
                if (returnvalBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001) &&
                            returnval_ != MixedValue.getDefaultInstance()) {
                        returnval_ =
                                MixedValue.newBuilder(returnval_).mergeFrom(value).buildPartial();
                    } else {
                        returnval_ = value;
                    }
                    onChanged();
                } else {
                    returnvalBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            public Builder clearReturnval() {
                if (returnvalBuilder_ == null) {
                    returnval_ = MixedValue.getDefaultInstance();
                    onChanged();
                } else {
                    returnvalBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public MixedValue.Builder getReturnvalBuilder() {
                bitField0_ |= 0x00000001;
                onChanged();
                return getReturnvalFieldBuilder().getBuilder();
            }

            public MixedValueOrBuilder getReturnvalOrBuilder() {
                if (returnvalBuilder_ != null) {
                    return returnvalBuilder_.getMessageOrBuilder();
                } else {
                    return returnval_;
                }
            }

            private com.google.protobuf.SingleFieldBuilder<
                    MixedValue, MixedValue.Builder, MixedValueOrBuilder>
            getReturnvalFieldBuilder() {
                if (returnvalBuilder_ == null) {
                    returnvalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            MixedValue, MixedValue.Builder, MixedValueOrBuilder>(
                            returnval_,
                            getParentForChildren(),
                            isClean());
                    returnval_ = null;
                }
                return returnvalBuilder_;
            }

            // optional string error = 2;
            private Object error_ = "";

            public boolean hasError() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getError() {
                Object ref = error_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    error_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setError(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                error_ = value;
                onChanged();
                return this;
            }

            public Builder clearError() {
                bitField0_ = (bitField0_ & ~0x00000002);
                error_ = getDefaultInstance().getError();
                onChanged();
                return this;
            }

            void setError(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                error_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:NaoAdapter.type.HAWActorRPCResponse)
        }

        static {
            defaultInstance = new HAWActorRPCResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:NaoAdapter.type.HAWActorRPCResponse)
    }

    public interface MixedValueOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional string string = 1;
        boolean hasString();

        String getString();

        // optional uint32 int = 2;
        boolean hasInt();

        int getInt();

        // optional float float = 3;
        boolean hasFloat();

        float getFloat();

        // optional bytes binary = 4;
        boolean hasBinary();

        com.google.protobuf.ByteString getBinary();

        // optional bool bool = 5;
        boolean hasBool();

        boolean getBool();

        // repeated .NaoAdapter.type.MixedValue array = 6;
        java.util.List<MixedValue>
        getArrayList();

        MixedValue getArray(int index);

        int getArrayCount();

        java.util.List<? extends MixedValueOrBuilder>
        getArrayOrBuilderList();

        MixedValueOrBuilder getArrayOrBuilder(
                int index);
    }

    public static final class MixedValue extends
            com.google.protobuf.GeneratedMessage
            implements MixedValueOrBuilder {
        // Use MixedValue.newBuilder() to construct.
        private MixedValue(Builder builder) {
            super(builder);
        }

        private MixedValue(boolean noInit) {
        }

        private static final MixedValue defaultInstance;

        public static MixedValue getDefaultInstance() {
            return defaultInstance;
        }

        public MixedValue getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Hawactormsg.internal_static_nao_MixedValue_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Hawactormsg.internal_static_nao_MixedValue_fieldAccessorTable;
        }

        private int bitField0_;
        // optional string string = 1;
        public static final int STRING_FIELD_NUMBER = 1;
        private Object string_;

        public boolean hasString() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getString() {
            Object ref = string_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    string_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getStringBytes() {
            Object ref = string_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                string_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional uint32 int = 2;
        public static final int INT_FIELD_NUMBER = 2;
        private int int_;

        public boolean hasInt() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public int getInt() {
            return int_;
        }

        // optional float float = 3;
        public static final int FLOAT_FIELD_NUMBER = 3;
        private float float_;

        public boolean hasFloat() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public float getFloat() {
            return float_;
        }

        // optional bytes binary = 4;
        public static final int BINARY_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString binary_;

        public boolean hasBinary() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public com.google.protobuf.ByteString getBinary() {
            return binary_;
        }

        // optional bool bool = 5;
        public static final int BOOL_FIELD_NUMBER = 5;
        private boolean bool_;

        public boolean hasBool() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public boolean getBool() {
            return bool_;
        }

        // repeated .NaoAdapter.type.MixedValue array = 6;
        public static final int ARRAY_FIELD_NUMBER = 6;
        private java.util.List<MixedValue> array_;

        public java.util.List<MixedValue> getArrayList() {
            return array_;
        }

        public java.util.List<? extends MixedValueOrBuilder>
        getArrayOrBuilderList() {
            return array_;
        }

        public int getArrayCount() {
            return array_.size();
        }

        public MixedValue getArray(int index) {
            return array_.get(index);
        }

        public MixedValueOrBuilder getArrayOrBuilder(
                int index) {
            return array_.get(index);
        }

        private void initFields() {
            string_ = "";
            int_ = 0;
            float_ = 0F;
            binary_ = com.google.protobuf.ByteString.EMPTY;
            bool_ = false;
            array_ = java.util.Collections.emptyList();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getStringBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeUInt32(2, int_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeFloat(3, float_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, binary_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBool(5, bool_);
            }
            for (int i = 0; i < array_.size(); i++) {
                output.writeMessage(6, array_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getStringBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, int_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(3, float_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, binary_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(5, bool_);
            }
            for (int i = 0; i < array_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(6, array_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static MixedValue parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static MixedValue parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static MixedValue parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static MixedValue parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static MixedValue parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static MixedValue parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static MixedValue parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static MixedValue parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static MixedValue parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static MixedValue parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(MixedValue prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements MixedValueOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Hawactormsg.internal_static_nao_MixedValue_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Hawactormsg.internal_static_nao_MixedValue_fieldAccessorTable;
            }

            // Construct using NaoAdapter.type.Hawactormsg.MixedValue.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getArrayFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                string_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                int_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                float_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000004);
                binary_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000008);
                bool_ = false;
                bitField0_ = (bitField0_ & ~0x00000010);
                if (arrayBuilder_ == null) {
                    array_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000020);
                } else {
                    arrayBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MixedValue.getDescriptor();
            }

            public MixedValue getDefaultInstanceForType() {
                return MixedValue.getDefaultInstance();
            }

            public MixedValue build() {
                MixedValue result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private MixedValue buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                MixedValue result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public MixedValue buildPartial() {
                MixedValue result = new MixedValue(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.string_ = string_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.int_ = int_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.float_ = float_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.binary_ = binary_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.bool_ = bool_;
                if (arrayBuilder_ == null) {
                    if (((bitField0_ & 0x00000020) == 0x00000020)) {
                        array_ = java.util.Collections.unmodifiableList(array_);
                        bitField0_ = (bitField0_ & ~0x00000020);
                    }
                    result.array_ = array_;
                } else {
                    result.array_ = arrayBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MixedValue) {
                    return mergeFrom((MixedValue) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MixedValue other) {
                if (other == MixedValue.getDefaultInstance()) return this;
                if (other.hasString()) {
                    setString(other.getString());
                }
                if (other.hasInt()) {
                    setInt(other.getInt());
                }
                if (other.hasFloat()) {
                    setFloat(other.getFloat());
                }
                if (other.hasBinary()) {
                    setBinary(other.getBinary());
                }
                if (other.hasBool()) {
                    setBool(other.getBool());
                }
                if (arrayBuilder_ == null) {
                    if (!other.array_.isEmpty()) {
                        if (array_.isEmpty()) {
                            array_ = other.array_;
                            bitField0_ = (bitField0_ & ~0x00000020);
                        } else {
                            ensureArrayIsMutable();
                            array_.addAll(other.array_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.array_.isEmpty()) {
                        if (arrayBuilder_.isEmpty()) {
                            arrayBuilder_.dispose();
                            arrayBuilder_ = null;
                            array_ = other.array_;
                            bitField0_ = (bitField0_ & ~0x00000020);
                            arrayBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getArrayFieldBuilder() : null;
                        } else {
                            arrayBuilder_.addAllMessages(other.array_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            string_ = input.readBytes();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            int_ = input.readUInt32();
                            break;
                        }
                        case 29: {
                            bitField0_ |= 0x00000004;
                            float_ = input.readFloat();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            binary_ = input.readBytes();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            bool_ = input.readBool();
                            break;
                        }
                        case 50: {
                            Builder subBuilder = MixedValue.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addArray(subBuilder.buildPartial());
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional string string = 1;
            private Object string_ = "";

            public boolean hasString() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getString() {
                Object ref = string_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    string_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setString(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                string_ = value;
                onChanged();
                return this;
            }

            public Builder clearString() {
                bitField0_ = (bitField0_ & ~0x00000001);
                string_ = getDefaultInstance().getString();
                onChanged();
                return this;
            }

            void setString(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                string_ = value;
                onChanged();
            }

            // optional uint32 int = 2;
            private int int_;

            public boolean hasInt() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public int getInt() {
                return int_;
            }

            public Builder setInt(int value) {
                bitField0_ |= 0x00000002;
                int_ = value;
                onChanged();
                return this;
            }

            public Builder clearInt() {
                bitField0_ = (bitField0_ & ~0x00000002);
                int_ = 0;
                onChanged();
                return this;
            }

            // optional float float = 3;
            private float float_;

            public boolean hasFloat() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public float getFloat() {
                return float_;
            }

            public Builder setFloat(float value) {
                bitField0_ |= 0x00000004;
                float_ = value;
                onChanged();
                return this;
            }

            public Builder clearFloat() {
                bitField0_ = (bitField0_ & ~0x00000004);
                float_ = 0F;
                onChanged();
                return this;
            }

            // optional bytes binary = 4;
            private com.google.protobuf.ByteString binary_ = com.google.protobuf.ByteString.EMPTY;

            public boolean hasBinary() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public com.google.protobuf.ByteString getBinary() {
                return binary_;
            }

            public Builder setBinary(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                binary_ = value;
                onChanged();
                return this;
            }

            public Builder clearBinary() {
                bitField0_ = (bitField0_ & ~0x00000008);
                binary_ = getDefaultInstance().getBinary();
                onChanged();
                return this;
            }

            // optional bool bool = 5;
            private boolean bool_;

            public boolean hasBool() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public boolean getBool() {
                return bool_;
            }

            public Builder setBool(boolean value) {
                bitField0_ |= 0x00000010;
                bool_ = value;
                onChanged();
                return this;
            }

            public Builder clearBool() {
                bitField0_ = (bitField0_ & ~0x00000010);
                bool_ = false;
                onChanged();
                return this;
            }

            // repeated .NaoAdapter.type.MixedValue array = 6;
            private java.util.List<MixedValue> array_ =
                    java.util.Collections.emptyList();

            private void ensureArrayIsMutable() {
                if (!((bitField0_ & 0x00000020) == 0x00000020)) {
                    array_ = new java.util.ArrayList<MixedValue>(array_);
                    bitField0_ |= 0x00000020;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    MixedValue, Builder, MixedValueOrBuilder> arrayBuilder_;

            public java.util.List<MixedValue> getArrayList() {
                if (arrayBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(array_);
                } else {
                    return arrayBuilder_.getMessageList();
                }
            }

            public int getArrayCount() {
                if (arrayBuilder_ == null) {
                    return array_.size();
                } else {
                    return arrayBuilder_.getCount();
                }
            }

            public MixedValue getArray(int index) {
                if (arrayBuilder_ == null) {
                    return array_.get(index);
                } else {
                    return arrayBuilder_.getMessage(index);
                }
            }

            public Builder setArray(
                    int index, MixedValue value) {
                if (arrayBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureArrayIsMutable();
                    array_.set(index, value);
                    onChanged();
                } else {
                    arrayBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setArray(
                    int index, Builder builderForValue) {
                if (arrayBuilder_ == null) {
                    ensureArrayIsMutable();
                    array_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    arrayBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addArray(MixedValue value) {
                if (arrayBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureArrayIsMutable();
                    array_.add(value);
                    onChanged();
                } else {
                    arrayBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addArray(
                    int index, MixedValue value) {
                if (arrayBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureArrayIsMutable();
                    array_.add(index, value);
                    onChanged();
                } else {
                    arrayBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addArray(
                    Builder builderForValue) {
                if (arrayBuilder_ == null) {
                    ensureArrayIsMutable();
                    array_.add(builderForValue.build());
                    onChanged();
                } else {
                    arrayBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addArray(
                    int index, Builder builderForValue) {
                if (arrayBuilder_ == null) {
                    ensureArrayIsMutable();
                    array_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    arrayBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllArray(
                    Iterable<? extends MixedValue> values) {
                if (arrayBuilder_ == null) {
                    ensureArrayIsMutable();
                    super.addAll(values, array_);
                    onChanged();
                } else {
                    arrayBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearArray() {
                if (arrayBuilder_ == null) {
                    array_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000020);
                    onChanged();
                } else {
                    arrayBuilder_.clear();
                }
                return this;
            }

            public Builder removeArray(int index) {
                if (arrayBuilder_ == null) {
                    ensureArrayIsMutable();
                    array_.remove(index);
                    onChanged();
                } else {
                    arrayBuilder_.remove(index);
                }
                return this;
            }

            public Builder getArrayBuilder(
                    int index) {
                return getArrayFieldBuilder().getBuilder(index);
            }

            public MixedValueOrBuilder getArrayOrBuilder(
                    int index) {
                if (arrayBuilder_ == null) {
                    return array_.get(index);
                } else {
                    return arrayBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends MixedValueOrBuilder>
            getArrayOrBuilderList() {
                if (arrayBuilder_ != null) {
                    return arrayBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(array_);
                }
            }

            public Builder addArrayBuilder() {
                return getArrayFieldBuilder().addBuilder(
                        MixedValue.getDefaultInstance());
            }

            public Builder addArrayBuilder(
                    int index) {
                return getArrayFieldBuilder().addBuilder(
                        index, MixedValue.getDefaultInstance());
            }

            public java.util.List<Builder>
            getArrayBuilderList() {
                return getArrayFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    MixedValue, Builder, MixedValueOrBuilder>
            getArrayFieldBuilder() {
                if (arrayBuilder_ == null) {
                    arrayBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            MixedValue, Builder, MixedValueOrBuilder>(
                            array_,
                            ((bitField0_ & 0x00000020) == 0x00000020),
                            getParentForChildren(),
                            isClean());
                    array_ = null;
                }
                return arrayBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:NaoAdapter.type.MixedValue)
        }

        static {
            defaultInstance = new MixedValue(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:NaoAdapter.type.MixedValue)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_nao_HAWActorRPCRequest_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_nao_HAWActorRPCRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_nao_HAWActorRPCResponse_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_nao_HAWActorRPCResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_nao_MixedValue_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_nao_MixedValue_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\021hawactormsg.proto\022\003nao\"U\n\022HAWActorRPCR" +
                        "equest\022\016\n\006module\030\001 \002(\t\022\016\n\006method\030\002 \002(\t\022\037" +
                        "\n\006params\030\003 \003(\0132\017.NaoAdapter.type.MixedValue\"H\n\023HAWAc" +
                        "torRPCResponse\022\"\n\treturnval\030\001 \001(\0132\017.NaoAdapter.type." +
                        "MixedValue\022\r\n\005error\030\002 \001(\t\"v\n\nMixedValue\022" +
                        "\016\n\006string\030\001 \001(\t\022\013\n\003int\030\002 \001(\r\022\r\n\005float\030\003 " +
                        "\001(\002\022\016\n\006binary\030\004 \001(\014\022\014\n\004bool\030\005 \001(\010\022\036\n\005arr" +
                        "ay\030\006 \003(\0132\017.NaoAdapter.type.MixedValue"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_nao_HAWActorRPCRequest_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_nao_HAWActorRPCRequest_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_nao_HAWActorRPCRequest_descriptor,
                                new String[]{"Module", "Method", "Params",},
                                HAWActorRPCRequest.class,
                                HAWActorRPCRequest.Builder.class);
                        internal_static_nao_HAWActorRPCResponse_descriptor =
                                getDescriptor().getMessageTypes().get(1);
                        internal_static_nao_HAWActorRPCResponse_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_nao_HAWActorRPCResponse_descriptor,
                                new String[]{"Returnval", "Error",},
                                HAWActorRPCResponse.class,
                                HAWActorRPCResponse.Builder.class);
                        internal_static_nao_MixedValue_descriptor =
                                getDescriptor().getMessageTypes().get(2);
                        internal_static_nao_MixedValue_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_nao_MixedValue_descriptor,
                                new String[]{"String", "Int", "Float", "Binary", "Bool", "Array",},
                                MixedValue.class,
                                MixedValue.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
